//
//  JSON RKI StateShape.swift
//  CoBaT
//
//  Created by Hartwig Hopfenzitz on 18.03.21.
//


// file generated by website "https://app.quicktype.io" which creates
// full JSON decode data structures and helper methodes out of JSON example data
// very usefull!!

// created file has been adjusted for internal use

// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let rKISSStateShapeJSON = try RKI_SS_StateShapeJSON(json)

import Foundation

// MARK: - RKI_SS_StateShapeJSON
struct RKI_SS_StateShapeJSON: Codable {
    var objectIdFieldName: String
    var uniqueIdField: RKI_SS_UniqueIdField
    var globalIdFieldName: String
    var geometryProperties: RKI_SS_GeometryProperties
    var geometryType: String
    var spatialReference: RKI_SS_SpatialReference
    var fields: [RKI_SS_Field]
    var features: [RKI_SS_Feature]

    enum CodingKeys: String, CodingKey {
        case objectIdFieldName = "objectIdFieldName"
        case uniqueIdField = "uniqueIdField"
        case globalIdFieldName = "globalIdFieldName"
        case geometryProperties = "geometryProperties"
        case geometryType = "geometryType"
        case spatialReference = "spatialReference"
        case fields = "fields"
        case features = "features"
    }
}

// MARK: RKI_SS_StateShapeJSON convenience initializers and mutators

extension RKI_SS_StateShapeJSON {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_StateShapeJSON.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        objectIdFieldName: String? = nil,
        uniqueIdField: RKI_SS_UniqueIdField? = nil,
        globalIdFieldName: String? = nil,
        geometryProperties: RKI_SS_GeometryProperties? = nil,
        geometryType: String? = nil,
        spatialReference: RKI_SS_SpatialReference? = nil,
        fields: [RKI_SS_Field]? = nil,
        features: [RKI_SS_Feature]? = nil
    ) -> RKI_SS_StateShapeJSON {
        return RKI_SS_StateShapeJSON(
            objectIdFieldName: objectIdFieldName ?? self.objectIdFieldName,
            uniqueIdField: uniqueIdField ?? self.uniqueIdField,
            globalIdFieldName: globalIdFieldName ?? self.globalIdFieldName,
            geometryProperties: geometryProperties ?? self.geometryProperties,
            geometryType: geometryType ?? self.geometryType,
            spatialReference: spatialReference ?? self.spatialReference,
            fields: fields ?? self.fields,
            features: features ?? self.features
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_Feature
struct RKI_SS_Feature: Codable {
    var attributes: RKI_SS_Attributes
    var geometry: RKI_SS_Geometry

    enum CodingKeys: String, CodingKey {
        case attributes = "attributes"
        case geometry = "geometry"
    }
}

// MARK: RKI_SS_Feature convenience initializers and mutators

extension RKI_SS_Feature {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_Feature.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        attributes: RKI_SS_Attributes? = nil,
        geometry: RKI_SS_Geometry? = nil
    ) -> RKI_SS_Feature {
        return RKI_SS_Feature(
            attributes: attributes ?? self.attributes,
            geometry: geometry ?? self.geometry
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_Attributes
struct RKI_SS_Attributes: Codable {
    var objectid1: Int
    var shapeArea: Double
    var shapeLength: Double
    var lanEwGEN: String

    enum CodingKeys: String, CodingKey {
        case objectid1 = "OBJECTID_1"
        case shapeArea = "Shape__Area"
        case shapeLength = "Shape__Length"
        case lanEwGEN = "LAN_ew_GEN"
    }
}

// MARK: RKI_SS_Attributes convenience initializers and mutators

extension RKI_SS_Attributes {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_Attributes.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        objectid1: Int? = nil,
        shapeArea: Double? = nil,
        shapeLength: Double? = nil,
        lanEwGEN: String? = nil
    ) -> RKI_SS_Attributes {
        return RKI_SS_Attributes(
            objectid1: objectid1 ?? self.objectid1,
            shapeArea: shapeArea ?? self.shapeArea,
            shapeLength: shapeLength ?? self.shapeLength,
            lanEwGEN: lanEwGEN ?? self.lanEwGEN
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_Geometry
struct RKI_SS_Geometry: Codable {
    var rings: [[[Double]]]

    enum CodingKeys: String, CodingKey {
        case rings = "rings"
    }
}

// MARK: RKI_SS_Geometry convenience initializers and mutators

extension RKI_SS_Geometry {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_Geometry.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        rings: [[[Double]]]? = nil
    ) -> RKI_SS_Geometry {
        return RKI_SS_Geometry(
            rings: rings ?? self.rings
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_Field
struct RKI_SS_Field: Codable {
    var name: String
    var type: String
    var alias: String
    var sqlType: String
    var domain: JSONNull?
    var defaultValue: JSONNull?
    var length: Int?

    enum CodingKeys: String, CodingKey {
        case name = "name"
        case type = "type"
        case alias = "alias"
        case sqlType = "sqlType"
        case domain = "domain"
        case defaultValue = "defaultValue"
        case length = "length"
    }
}

// MARK: RKI_SS_Field convenience initializers and mutators

extension RKI_SS_Field {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_Field.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        name: String? = nil,
        type: String? = nil,
        alias: String? = nil,
        sqlType: String? = nil,
        domain: JSONNull?? = nil,
        defaultValue: JSONNull?? = nil,
        length: Int?? = nil
    ) -> RKI_SS_Field {
        return RKI_SS_Field(
            name: name ?? self.name,
            type: type ?? self.type,
            alias: alias ?? self.alias,
            sqlType: sqlType ?? self.sqlType,
            domain: domain ?? self.domain,
            defaultValue: defaultValue ?? self.defaultValue,
            length: length ?? self.length
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_GeometryProperties
struct RKI_SS_GeometryProperties: Codable {
    var shapeAreaFieldName: String
    var shapeLengthFieldName: String
    var units: String

    enum CodingKeys: String, CodingKey {
        case shapeAreaFieldName = "shapeAreaFieldName"
        case shapeLengthFieldName = "shapeLengthFieldName"
        case units = "units"
    }
}

// MARK: RKI_SS_GeometryProperties convenience initializers and mutators

extension RKI_SS_GeometryProperties {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_GeometryProperties.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        shapeAreaFieldName: String? = nil,
        shapeLengthFieldName: String? = nil,
        units: String? = nil
    ) -> RKI_SS_GeometryProperties {
        return RKI_SS_GeometryProperties(
            shapeAreaFieldName: shapeAreaFieldName ?? self.shapeAreaFieldName,
            shapeLengthFieldName: shapeLengthFieldName ?? self.shapeLengthFieldName,
            units: units ?? self.units
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_SpatialReference
struct RKI_SS_SpatialReference: Codable {
    var wkid: Int
    var latestWkid: Int

    enum CodingKeys: String, CodingKey {
        case wkid = "wkid"
        case latestWkid = "latestWkid"
    }
}

// MARK: RKI_SS_SpatialReference convenience initializers and mutators

extension RKI_SS_SpatialReference {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_SpatialReference.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        wkid: Int? = nil,
        latestWkid: Int? = nil
    ) -> RKI_SS_SpatialReference {
        return RKI_SS_SpatialReference(
            wkid: wkid ?? self.wkid,
            latestWkid: latestWkid ?? self.latestWkid
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - RKI_SS_UniqueIdField
struct RKI_SS_UniqueIdField: Codable {
    var name: String
    var isSystemMaintained: Bool

    enum CodingKeys: String, CodingKey {
        case name = "name"
        case isSystemMaintained = "isSystemMaintained"
    }
}

// MARK: RKI_SS_UniqueIdField convenience initializers and mutators

extension RKI_SS_UniqueIdField {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(RKI_SS_UniqueIdField.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        name: String? = nil,
        isSystemMaintained: Bool? = nil
    ) -> RKI_SS_UniqueIdField {
        return RKI_SS_UniqueIdField(
            name: name ?? self.name,
            isSystemMaintained: isSystemMaintained ?? self.isSystemMaintained
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Helper functions for creating encoders and decoders

//func newJSONDecoder() -> JSONDecoder {
//    let decoder = JSONDecoder()
//    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
//        decoder.dateDecodingStrategy = .iso8601
//    }
//    return decoder
//}
//
//func newJSONEncoder() -> JSONEncoder {
//    let encoder = JSONEncoder()
//    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
//        encoder.dateEncodingStrategy = .iso8601
//    }
//    return encoder
//}
//
//// MARK: - Encode/decode helpers
//
//class JSONNull: Codable, Hashable {
//
//    public static func == (lhs: JSONNull, rhs: JSONNull) -> Bool {
//        return true
//    }
//
//    public var hashValue: Int {
//        return 0
//    }
//
//    public func hash(into hasher: inout Hasher) {
//        // No-op
//    }
//
//    public init() {}
//
//    public required init(from decoder: Decoder) throws {
//        let container = try decoder.singleValueContainer()
//        if !container.decodeNil() {
//            throw DecodingError.typeMismatch(JSONNull.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for JSONNull"))
//        }
//    }
//
//    public func encode(to encoder: Encoder) throws {
//        var container = encoder.singleValueContainer()
//        try container.encodeNil()
//    }
//}
